pipeline {
    agent any
    stages {
        stage ('deliverJsonPayload') {
            echo "${RootSchemaGcp}"
        }
    }
    post {
        success {
            echo "Test succeeded"
        }
        failure {
            echo "Test failed"
        }
    }
}