pipeline {
    agent any
    stages {
        stage ('deliverJsonPayload') {
            steps{
                echo "${params.RootSchemaGcp}"
            }
        }
    }
    post {
        success {
            echo "Test succeeded"
        }
        failure {
            echo "Test failed"
        }
    }
}